---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
     - "dependencies"
     - "javascript"
     - "type::chore"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    groups:
      security:
        update-types:
          - "patch"
      gatsby:
        patterns:
          - "gatsby"
          - "gatsby-*"
      bugsnag:
        patterns:
          - "@bugsnag/*"
      docsearch:
        patterns:
          - "docsearch*"
      react:
        patterns:
          - "react"
          - "react-dom"
      "babel":
        patterns:
          - "@babel/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    schedule:
      interval: "weekly"
