name: scrape
on: 
  push:
    branches:
      release
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎d
        uses: actions/checkout@v5
      # when scraping the site, inject secrets as environment variables
      # then pass their values into the Docker container using "-e" syntax
      # and inject config.json contents as another variable
      - name: scrape the site 🧽
        env:
          ALGOLIA_APP_ID: ${{ secrets.KURL_SH_ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.KURL_SH_ALGOLIA_API_KEY }}
        run: |
          docker run \
          -e ALGOLIA_APP_ID -e ALGOLIA_API_KEY \
          -e CONFIG="$(cat algolia-config.json)" \
          algolia/docsearch-scraper
