name: preview

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:

  deploy-staging-netlify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: yarn
      - name: dependencies
        run: make deps
      - name: playwright
        run: npx playwright install --with-deps
      - name: build
        run: make build-staging

      - name: release
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: public
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy preview staging.kurl.sh from GitHub Actions"
          github-deployment-environment: preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 9cc8b96a-2c23-4f71-bb0f-cbdc19ccbf76
        timeout-minutes: 5
